title: Spotty Finder
description: Spotty Finder is an application that allows you to track your locations.
baseurl: "/"
url: "http://spottyfinder.github.io"

# Build settings
markdown: kramdown

#sass:
#  style: compressed
